DROP SCHEMA IF EXISTS public cascade;

CREATE SCHEMA public;

CREATE TABLE vet (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text,
    last_name text
  );
    
  
  CREATE TABLE specialty (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text
  );
  
  
  
  
  CREATE TABLE vet_specialty (
    vet_id INT NOT NULL REFERENCES vet(id),
    specialty_id INT NOT NULL REFERENCES specialty(id),
    UNIQUE (vet_id,specialty_id)
  );
  
  
  
  CREATE TABLE type (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text
  );
  
    
  CREATE TABLE owner (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text,
    last_name text,
    address text,
    city text,
    telephone text
  );
  
  
  
  
  CREATE TABLE pet (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    birth_date DATE,
    type_id INT NOT NULL REFERENCES type(id),
    owner_id INT NOT NULL REFERENCES owner(id)
  );
    
  
  CREATE TABLE visit (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id INT NOT NULL REFERENCES pet(id),
    vet_id INT NOT NULL REFERENCES vet(id),
    visit_date DATE,
    description text
  );
  


INSERT INTO vet VALUES (DEFAULT, 'James', 'Carter');
INSERT INTO vet VALUES (DEFAULT, 'Helen', 'Leary');
INSERT INTO vet VALUES (DEFAULT, 'Linda', 'Douglas');
INSERT INTO vet VALUES (DEFAULT, 'Rafael', 'Ortega');
INSERT INTO vet VALUES (DEFAULT, 'Henry', 'Stevens');
INSERT INTO vet VALUES (DEFAULT, 'Sharon', 'Jenkins');

INSERT INTO specialty VALUES (DEFAULT, 'radiology');
INSERT INTO specialty VALUES (DEFAULT, 'surgery');
INSERT INTO specialty VALUES (DEFAULT, 'dentistry');

INSERT INTO vet_specialty VALUES (2, 1);
INSERT INTO vet_specialty VALUES (3, 2);
INSERT INTO vet_specialty VALUES (3, 3);
INSERT INTO vet_specialty VALUES (4, 2);
INSERT INTO vet_specialty VALUES (5, 1);

INSERT INTO type VALUES (DEFAULT, 'cat');
INSERT INTO type VALUES (DEFAULT, 'dog');
INSERT INTO type VALUES (DEFAULT, 'lizard');
INSERT INTO type VALUES (DEFAULT, 'snake');
INSERT INTO type VALUES (DEFAULT, 'bird');
INSERT INTO type VALUES (DEFAULT, 'hamster');

INSERT INTO owner VALUES (DEFAULT, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO owner VALUES (DEFAULT, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO owner VALUES (DEFAULT, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO owner VALUES (DEFAULT, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO owner VALUES (DEFAULT, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO owner VALUES (DEFAULT, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO owner VALUES (DEFAULT, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO owner VALUES (DEFAULT, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO owner VALUES (DEFAULT, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO owner VALUES (DEFAULT, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO pet VALUES (DEFAULT, 'Leo', '2000-09-07', 1, 1);
INSERT INTO pet VALUES (DEFAULT, 'Basil', '2002-08-06', 6, 2);
INSERT INTO pet VALUES (DEFAULT, 'Rosy', '2001-04-17', 2, 3);
INSERT INTO pet VALUES (DEFAULT, 'Jewel', '2000-03-07', 2, 3);
INSERT INTO pet VALUES (DEFAULT, 'Iggy', '2000-11-30', 3, 4);
INSERT INTO pet VALUES (DEFAULT, 'George', '2000-01-20', 4, 5);
INSERT INTO pet VALUES (DEFAULT, 'Samantha', '1995-09-04', 1, 6);
INSERT INTO pet VALUES (DEFAULT, 'Max', '1995-09-04', 1, 6);
INSERT INTO pet VALUES (DEFAULT, 'Lucky', '1999-08-06', 5, 7);
INSERT INTO pet VALUES (DEFAULT, 'Mulligan', '1997-02-24', 2, 8);
INSERT INTO pet VALUES (DEFAULT, 'Freddy', '2000-03-09', 5, 9);
INSERT INTO pet VALUES (DEFAULT, 'Lucky', '2000-06-24', 2, 10);
INSERT INTO pet VALUES (DEFAULT, 'Sly', '2002-06-08', 1, 10);

INSERT INTO visit VALUES (DEFAULT, 7, 1, '2010-03-04', 'rabies shot');
INSERT INTO visit VALUES (DEFAULT, 8, 2, '2011-03-04', 'rabies shot');
INSERT INTO visit VALUES (DEFAULT, 8, 4, '2009-06-04', 'neutered');
INSERT INTO visit VALUES (DEFAULT, 7, 4, '2008-09-04', 'spayed');